modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="berrfect"
version="1.0.1"
displayName="Berrfect"
logoFile="icon.png"
authors="Gumillea"
description='''
A simple addon for Berry Good that makes more berries less annoying to eat.
'''
[[dependencies.berrfect]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.berrfect]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.berrfect]]
modId="blueprint"
mandatory=true
versionRange="[6.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.berrfect]]
modId="berry_good"
mandatory=true
versionRange="[6.1.0,)"
ordering="AFTER"
side="BOTH"